import { expect, test } from '@playwright/test';

import { BookCatalogPage, BookEventTypePage } from '../pages/book-page';
import { EventTypeEditPage } from '../pages/event-type-edit-page';
import { EventTypeNewPage } from '../pages/event-type-new-page';
import { EventTypesPage } from '../pages/event-types-page';
import { EventsPage } from '../pages/events-page';
import { HomePage } from '../pages/home-page';

test.describe.configure({ mode: 'serial' });

test('navigates from home page to booking catalog', async ({ page }) => {
  const homePage = new HomePage(page);
  const bookCatalogPage = new BookCatalogPage(page);

  await homePage.open();

  await expect(homePage.heading()).toBeVisible();
  await homePage.clickCta();

  await expect(bookCatalogPage.title()).toBeVisible();
  await expect(page).toHaveURL(/\/book$/);
  await expect(bookCatalogPage.eventTypesList()).toBeVisible();
  await expect(bookCatalogPage.eventTypeCards().first()).toBeVisible();
});

test('opens admin from header and defaults to events page', async ({ page }) => {
  const homePage = new HomePage(page);
  const eventsPage = new EventsPage(page);
  const eventTypesPage = new EventTypesPage(page);

  await homePage.open();
  await homePage.adminNavLink().click();

  await expect(page).toHaveURL(/\/admin\/events$/);
  await expect(eventsPage.sidebar()).toBeVisible();
  await expect(eventsPage.title()).toBeVisible();

  await eventsPage.eventTypesNavItem().click();
  await expect(page).toHaveURL(/\/admin\/event-types$/);
  await expect(eventTypesPage.title()).toBeVisible();
});

test('books a slot with notes and shows booking in events list', async ({ page }) => {
  const bookCatalogPage = new BookCatalogPage(page);
  const bookEventTypePage = new BookEventTypePage(page);
  const eventsPage = new EventsPage(page);
  const clientName = `Playwright User ${Date.now()}`;
  const clientEmail = `playwright-${Date.now()}@example.com`;
  const notes = `Additional notes ${Date.now()}`;
  const eventTypeSlug = 'quick-call';
  const eventTypeName = 'Встреча 15 минут';

  await bookCatalogPage.open();
  await expect(bookCatalogPage.title()).toBeVisible();
  await bookCatalogPage.openEventTypeBySlug(eventTypeSlug);

  await expect(page).toHaveURL(new RegExp(`/book/${eventTypeSlug}$`));
  await expect(bookEventTypePage.title()).toContainText(eventTypeName);

  await bookEventTypePage.selectFirstDateWithFreeSlots();
  await bookEventTypePage.selectFirstAvailableSlot();
  await bookEventTypePage.proceedToConfirmStep();

  await expect(bookEventTypePage.confirmHeading()).toBeVisible();
  await bookEventTypePage.fillContactForm(clientName, clientEmail);
  await bookEventTypePage.fillNotes(notes);
  await bookEventTypePage.submitBooking();

  await expect(bookEventTypePage.successMessage()).toBeVisible();
  await expect(bookEventTypePage.successMessage()).toContainText('Встреча создана');
  await expect(bookEventTypePage.successCard()).toContainText('Детали:');
  await expect(bookEventTypePage.successCard()).toContainText('Описание');
  await expect(bookEventTypePage.successCard()).toContainText(eventTypeName);
  await expect(bookEventTypePage.successCard()).toContainText('Когда');
  await expect(bookEventTypePage.successCard()).toContainText('Заметки');
  await expect(bookEventTypePage.successCard()).toContainText(notes);
  await expect(bookEventTypePage.bookAgainButton()).toBeVisible();

  await eventsPage.open();

  await expect(eventsPage.title()).toBeVisible();
  await expect(eventsPage.bookingCardByClient(clientName)).toContainText(clientEmail);
  await expect(eventsPage.bookingCardByClientAndNote(clientName, notes)).toBeVisible();
});

test('creates, edits and deletes event type in admin', async ({ page }) => {
  const eventTypesPage = new EventTypesPage(page);
  const eventTypeNewPage = new EventTypeNewPage(page);
  const eventTypeEditPage = new EventTypeEditPage(page);
  const suffix = Date.now();
  const createdName = `Call ${suffix}`;
  const createdSlug = `call-${suffix}`;
  const updatedName = `Updated Call ${suffix}`;

  await eventTypesPage.open();

  await expect(eventTypesPage.title()).toBeVisible();
  await eventTypesPage.createLink().click();

  await expect(eventTypeNewPage.title()).toBeVisible();
  await expect(page).toHaveURL(/\/admin\/event-types\/new$/);
  await expect(eventTypeNewPage.form()).toBeVisible();

  await eventTypeNewPage.nameInput().fill(createdName);
  await eventTypeNewPage.slugInput().fill(createdSlug);
  await eventTypeNewPage.descriptionInput().fill('Autogenerated test event type');
  await eventTypeNewPage.durationInput().fill('15');
  await eventTypeNewPage.saveButton().click();

  await expect(page).toHaveURL(/\/admin\/event-types$/);
  await expect(eventTypesPage.cardByName(createdName)).toHaveCount(1);

  await eventTypesPage.cardByName(createdName).getByTestId('event-type-edit-button').click();
  await expect(page).toHaveURL(/\/admin\/event-types\/[^/]+$/);
  await expect(eventTypeEditPage.title()).toBeVisible();
  await expect(eventTypeEditPage.form()).toBeVisible();

  await eventTypeEditPage.nameInput().fill(updatedName);
  await eventTypeEditPage.saveButton().click();

  await expect(page).toHaveURL(/\/admin\/event-types$/);
  await expect(eventTypesPage.cardByName(updatedName)).toHaveCount(1);

  page.once('dialog', (dialog) => void dialog.accept());
  await eventTypesPage.cardByName(updatedName).getByTestId('event-type-delete-button').click();
  await expect(eventTypesPage.status()).toContainText('удален');
});
