version: 2
updates:
  # NPM ecosystem
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"

  # GitHub Actions ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
